export interface PoHeader {

  id?: number;                 // UI only (later from API)
  poNumber?: string;           // Generated by backend later

  poDate: Date;

  supplierId: number;
  supplierName?: string;       // UI display only

  priceListId: number;         // auto-picked (hidden from UI)
  priceListName?: string;      // optional display

  status: 'DRAFT' | 'APPROVED' | 'RECEIVED' | 'CLOSED';

  remarks?: string;
}
